export const revalidate = 86400
import Navbar from '@/components/ui/Navbar'
import Footer from '@/components/ui/Footer'
import type { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'ACUVUE® 2 precio en República Dominicana 2026 — ContactGo', description: 'Precio de ACUVUE® 2 en RD: RD$3,600. Lentes quincenales hidrogel J&J. 100% originales. Entrega 24-48h en toda República Dominicana.',
  alternates: { canonical: 'https://www.contactgo.net/blog/acuvue-2-precio-republica-dominicana' },
  openGraph: { type: 'article', title: 'ACUVUE® 2 precio en República Dominicana 2026', description: 'Precio de ACUVUE® 2 en RD: RD$3,600. Lentes quincenales hidrogel J&J. 100% originales. Entrega 24-48h en toda República Dominicana.', url: 'https://www.contactgo.net/blog/acuvue-2-precio-republica-dominicana', siteName: 'ContactGo', locale: 'es_DO', images: [{ url: 'https://www.contactgo.net/blog/acuvue-2-precio-republica-dominicana.webp', width: 1200, height: 630, alt: 'ACUVUE® 2 precio en República Dominicana 2026' }] },
}
export default function Page() {
  return (<><Navbar /><main className="max-w-2xl mx-auto px-4 py-12 pb-24">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([
      {"@context":"https://schema.org","@type":"Article","headline":"ACUVUE® 2 precio en República Dominicana 2026","description":"Precio de ACUVUE® 2 en RD: RD$3,600. Lentes quincenales hidrogel J&J. 100% originales. Entrega 24-48h en toda República Dominicana.","author":{"@type":"Organization","name":"Equipo ContactGo"},"publisher":{"@type":"Organization","name":"ContactGo","url":"https://www.contactgo.net","logo":{"@type":"ImageObject","url":"https://www.contactgo.net/logo.png"}},"datePublished":"2026-07-02","dateModified":"2026-07-02","url":"https://www.contactgo.net/blog/acuvue-2-precio-republica-dominicana","inLanguage":"es-DO"},
      {"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":'¿Cuánto cuestan los ACUVUE 2 en República Dominicana?',"acceptedAnswer":{"@type":"Answer","text":'En ContactGo los ACUVUE 2 cuestan RD$3,600 la caja de 6 lentes quincenales. Son los lentes J&J más económicos disponibles en RD, con entrega en 24-48 horas en toda la República Dominicana.'}},{"@type":"Question","name":'¿ACUVUE 2 o ACUVUE Oasys — cuál es mejor?',"acceptedAnswer":{"@type":"Answer","text":'ACUVUE Oasys es superior: silicona hidrogel (Dk/t 147 vs 26), HYDRACLEAR Plus para mayor hidratación y mayor comodidad en uso prolongado. Por RD$275 más por caja, vale la diferencia para uso diario de 8+ horas. ACUVUE 2 es una opción si el presupuesto es prioritario.'}},{"@type":"Question","name":'¿Se pueden comprar ACUVUE 2 originales en RD?',"acceptedAnswer":{"@type":"Answer","text":'Sí. En ContactGo tienes ACUVUE 2 100% originales de Johnson & Johnson con entrega en 24-48h. Sellados de fábrica, con número de lote y fecha de caducidad verificables.'}}]},
      {"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Inicio","item":"https://www.contactgo.net"},{"@type":"ListItem","position":2,"name":"Blog","item":"https://www.contactgo.net/blog"},{"@type":"ListItem","position":3,"name":"ACUVUE® 2 precio en República Dominicana 2026","item":"https://www.contactgo.net/blog/acuvue-2-precio-republica-dominicana"}]}
    ]) }} />
    <div className="flex items-center gap-1.5 text-xs text-gray-400 mb-4"><a href="/" className="hover:text-primary-600">Inicio</a><span>/</span><a href="/blog" className="hover:text-primary-600">Blog</a><span>/</span><span className="text-gray-600 truncate">ACUVUE® 2 precio en República Dominicana</span></div>
    <span className="text-xs font-semibold text-green-600 bg-green-50 px-2 py-0.5 rounded-full">💰 Precios 2026</span>
    <h1 className="font-display text-3xl font-bold text-gray-900 mt-3 mb-2">ACUVUE® 2 precio en República Dominicana 2026</h1>
    <div className="flex items-center gap-3 mb-6 p-4 bg-blue-50 border border-blue-100 rounded-2xl">
      <div className="w-10 h-10 rounded-full bg-primary-600 flex items-center justify-center shrink-0"><span className="text-white font-bold text-sm">CG</span></div>
      <div><p className="text-sm font-bold text-gray-900">Equipo ContactGo</p><p className="text-xs text-gray-500">Especialistas en salud visual · 6 min · Julio 2026</p></div>
    </div>
    <div className="space-y-8 text-gray-700 leading-relaxed">
      <p>Los <strong>ACUVUE® 2</strong> son lentes de contacto disponibles en ContactGo a <strong>RD$3,600</strong> con entrega en 24-48 horas en toda República Dominicana. Esta guía tiene el precio actualizado, características principales y cómo pedirlos.</p>
    <section id="precio">
      <h2 className="font-display text-2xl font-bold text-gray-900 mb-4">Precio en República Dominicana — Julio 2026</h2>
      <div className="bg-green-50 border-2 border-green-200 rounded-2xl p-5 mb-4">
        <div className="flex items-baseline gap-2"><span className="text-4xl font-black text-gray-900">RD$3,600</span><span className="text-gray-500 text-sm">Caja de 6 lentes — quincenal</span></div>
        <div className="flex gap-2 mt-4">
          <a href="/producto/acuvue-2-lentes-contacto-quincenales-dominicana" className="flex-1 bg-primary-600 text-white font-bold px-4 py-2.5 rounded-xl text-xs text-center hover:bg-primary-700 transition-colors">Comprar ACUVUE® 2 →</a>
          <a href="https://wa.me/18295430580" target="_blank" rel="noopener noreferrer" className="flex-1 bg-[#25D366] text-white font-bold px-4 py-2.5 rounded-xl text-xs text-center">Pedir por WhatsApp</a>
        </div>
      </div>
      <p className="text-sm text-gray-700 mt-3">ACUVUE 2 es el lente quincenal clásico de Johnson &amp; Johnson, fabricado con hidrogel de alta calidad. Aunque no es silicona hidrogel como el ACUVUE Oasys, sigue siendo una opción confiable para quienes buscan el menor precio en la línea ACUVUE. Dk/t de 26 — recomendado para uso de hasta 8-10 horas diarias.</p>
    <div className="bg-blue-50 border border-blue-100 rounded-xl p-4 mt-4 text-sm">
      <p className="font-bold text-blue-800 mb-1">💡 ACUVUE 2 vs ACUVUE Oasys</p>
      <p className="text-blue-700">ACUVUE 2 es hidrogel convencional (RD$3,600). ACUVUE Oasys es silicona hidrogel con HYDRACLEAR Plus (RD$3,875). Por solo RD$275 más, ACUVUE Oasys ofrece 5x más oxígeno y tecnología de hidratación superior. Para uso intensivo, Oasys es la mejor inversión.</p>
    </div>
    </section>
      <section id="productos"><h2 className="font-display text-xl font-bold text-gray-900 mb-4">Disponibles en ContactGo — Entrega 24-48h</h2>
        <div className="space-y-2">            <a href="/producto/acuvue-2-lentes-contacto-quincenales-dominicana" className="flex items-center justify-between p-3 border border-gray-100 rounded-xl hover:border-primary-200 hover:bg-primary-50/20 transition-all group"><div><p className="text-sm font-semibold text-gray-900 group-hover:text-primary-600">ACUVUE® 2</p><p className="text-xs text-gray-500">Lentes quincenales hidrogel J&J</p></div><span className="font-black text-gray-900 text-sm shrink-0 ml-3">RD$3,600</span></a>
            <a href="/producto/acuvue-oasys-hydraclear-plus-lentes-contacto-quincenal-dominicana" className="flex items-center justify-between p-3 border border-gray-100 rounded-xl hover:border-primary-200 hover:bg-primary-50/20 transition-all group"><div><p className="text-sm font-semibold text-gray-900 group-hover:text-primary-600">ACUVUE Oasys 6u</p><p className="text-xs text-gray-500">Caja de 6 lentes — quincenal</p></div><span className="font-black text-gray-900 text-sm shrink-0 ml-3">RD$3,875</span></a></div>
        <a href="/catalogo" className="mt-3 inline-block text-sm text-primary-600 font-semibold hover:underline">Ver catálogo completo →</a>
      </section>
      <section id="faq"><h2 className="font-display text-2xl font-bold text-gray-900 mb-5">Preguntas frecuentes</h2><div className="space-y-3">          <details className="group bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden"><summary className="flex items-center justify-between p-4 cursor-pointer font-semibold text-gray-900 text-sm list-none">¿Cuánto cuestan los ACUVUE 2 en República Dominicana?<svg className="w-4 h-4 text-gray-400 group-open:rotate-180 transition-transform shrink-0 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7"/></svg></summary><p className="px-4 pb-4 text-gray-600 text-sm leading-relaxed">En ContactGo los ACUVUE 2 cuestan RD$3,600 la caja de 6 lentes quincenales. Son los lentes J&J más económicos disponibles en RD, con entrega en 24-48 horas en toda la República Dominicana.</p></details>
          <details className="group bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden"><summary className="flex items-center justify-between p-4 cursor-pointer font-semibold text-gray-900 text-sm list-none">¿ACUVUE 2 o ACUVUE Oasys — cuál es mejor?<svg className="w-4 h-4 text-gray-400 group-open:rotate-180 transition-transform shrink-0 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7"/></svg></summary><p className="px-4 pb-4 text-gray-600 text-sm leading-relaxed">ACUVUE Oasys es superior: silicona hidrogel (Dk/t 147 vs 26), HYDRACLEAR Plus para mayor hidratación y mayor comodidad en uso prolongado. Por RD$275 más por caja, vale la diferencia para uso diario de 8+ horas. ACUVUE 2 es una opción si el presupuesto es prioritario.</p></details>
          <details className="group bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden"><summary className="flex items-center justify-between p-4 cursor-pointer font-semibold text-gray-900 text-sm list-none">¿Se pueden comprar ACUVUE 2 originales en RD?<svg className="w-4 h-4 text-gray-400 group-open:rotate-180 transition-transform shrink-0 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7"/></svg></summary><p className="px-4 pb-4 text-gray-600 text-sm leading-relaxed">Sí. En ContactGo tienes ACUVUE 2 100% originales de Johnson & Johnson con entrega en 24-48h. Sellados de fábrica, con número de lote y fecha de caducidad verificables.</p></details></div></section>
      <div className="grid gap-2"><h3 className="font-bold text-gray-900 text-lg">Artículos relacionados</h3>            <a href="/blog/acuvue-oasys-precio-republica-dominicana" className="border border-gray-100 rounded-xl p-3 hover:border-primary-200 hover:bg-primary-50/20 transition-all"><p className="text-sm font-semibold text-primary-600">→ ACUVUE Oasys precio en RD</p><p className="text-xs text-gray-500 mt-0.5">La versión premium de ACUVUE</p></a>
            <a href="/blog/cuanto-cuestan-lentes-contacto-rd" className="border border-gray-100 rounded-xl p-3 hover:border-primary-200 hover:bg-primary-50/20 transition-all"><p className="text-sm font-semibold text-primary-600">→ Precios de todos los lentes en RD</p><p className="text-xs text-gray-500 mt-0.5">Comparativa completa de marcas</p></a>
            <a href="/marca/acuvue" className="border border-gray-100 rounded-xl p-3 hover:border-primary-200 hover:bg-primary-50/20 transition-all"><p className="text-sm font-semibold text-primary-600">→ Toda la línea ACUVUE en ContactGo</p><p className="text-xs text-gray-500 mt-0.5">ACUVUE 2, Oasys, Moist y más</p></a></div>
    </div>
    <div className="border-l-4 border-blue-500 bg-blue-50 rounded-r-xl p-4 my-6"><p className="font-bold text-gray-900 text-sm">Verificado · Equipo ContactGo · Julio 2026</p></div>
    <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 mt-6 text-sm text-amber-900"><strong>Aviso médico:</strong> Ante molestias oculares consulta a tu especialista.</div>
    <div className="mt-10 bg-gradient-to-br from-primary-50 to-teal-50 border border-primary-100 rounded-2xl p-6 text-center">
      <h3 className="font-bold text-gray-900 text-lg mb-2">Recibe en toda República Dominicana en 24-48h</h3>
      <p className="text-sm text-gray-500 mb-4">100% originales · Pago seguro con AZUL/Banco Popular</p>
      <div className="flex flex-col sm:flex-row gap-3 justify-center">
        <a href="/catalogo" className="inline-flex items-center justify-center gap-2 bg-primary-600 text-white font-bold px-6 py-3 rounded-xl hover:bg-primary-700 transition-colors text-sm">Ver catálogo →</a>
        <a href="/receta" className="inline-flex items-center justify-center gap-2 bg-white border border-primary-200 text-primary-600 font-bold px-6 py-3 rounded-xl hover:bg-primary-50 transition-colors text-sm">Calcular mi receta</a>
        <a href="https://wa.me/18295430580" target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 bg-[#25D366] text-white font-bold px-6 py-3 rounded-xl hover:bg-[#20ba58] transition-colors text-sm">Comprar por WhatsApp</a>
      </div>
    </div>
  </main><Footer /></>)
}
