export const revalidate = 86400
import Navbar from '@/components/ui/Navbar'
import Footer from '@/components/ui/Footer'
import type { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'Proclear® Sphere precio en República Dominicana 2026 — ContactGo', description: 'Precio de Proclear® Sphere en RD: RD$3,200. Lentes mensuales PC Technology CooperVision. 100% originales. Entrega 24-48h en toda República Dominicana.',
  alternates: { canonical: 'https://www.contactgo.net/blog/proclear-sphere-precio-republica-dominicana' },
  openGraph: { type: 'article', title: 'Proclear® Sphere precio en República Dominicana 2026', description: 'Precio de Proclear® Sphere en RD: RD$3,200. Lentes mensuales PC Technology CooperVision. 100% originales. Entrega 24-48h en toda República Dominicana.', url: 'https://www.contactgo.net/blog/proclear-sphere-precio-republica-dominicana', siteName: 'ContactGo', locale: 'es_DO', images: [{ url: 'https://www.contactgo.net/blog/proclear-sphere-precio-republica-dominicana.webp', width: 1200, height: 630, alt: 'Proclear® Sphere precio en República Dominicana 2026' }] },
}
export default function Page() {
  return (<><Navbar /><main className="max-w-2xl mx-auto px-4 py-12 pb-24">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([
      {"@context":"https://schema.org","@type":"Article","headline":"Proclear® Sphere precio en República Dominicana 2026","description":"Precio de Proclear® Sphere en RD: RD$3,200. Lentes mensuales PC Technology CooperVision. 100% originales. Entrega 24-48h en toda República Dominicana.","author":{"@type":"Organization","name":"Equipo ContactGo"},"publisher":{"@type":"Organization","name":"ContactGo","url":"https://www.contactgo.net","logo":{"@type":"ImageObject","url":"https://www.contactgo.net/logo.png"}},"datePublished":"2026-07-02","dateModified":"2026-07-02","url":"https://www.contactgo.net/blog/proclear-sphere-precio-republica-dominicana","inLanguage":"es-DO"},
      {"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":'¿Cuánto cuestan los Proclear Sphere en República Dominicana?',"acceptedAnswer":{"@type":"Answer","text":'En ContactGo los Proclear Sphere cuestan RD$3,200 la caja de 6 lentes mensuales. Son los lentes mensuales más económicos disponibles en RD, con entrega en 24-48h en toda la República Dominicana.'}},{"@type":"Question","name":'¿Proclear Sphere o Biofinity — cuál elegir?',"acceptedAnswer":{"@type":"Answer","text":'Biofinity (RD$4,750) usa silicona hidrogel Comfilcon A con Dk/t 160 — mucho mayor oxígeno. Proclear Sphere usa hidrogel Omafilcon A con Dk/t 28. Para uso de hasta 8h, Proclear Sphere es suficiente y más económico. Para uso de 10h+, Biofinity es mejor opción.'}},{"@type":"Question","name":'¿Proclear Sphere es para astigmatismo?',"acceptedAnswer":{"@type":"Answer","text":'No. Proclear Sphere es un lente esférico, para quienes no tienen astigmatismo (o tienen CYL muy leve no corregible con lentes de contacto). Si tienes astigmatismo (CYL en tu receta), necesitas lentes tóricos como Biofinity Toric o ACUVUE Oasys for Astigmatism.'}}]},
      {"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Inicio","item":"https://www.contactgo.net"},{"@type":"ListItem","position":2,"name":"Blog","item":"https://www.contactgo.net/blog"},{"@type":"ListItem","position":3,"name":"Proclear® Sphere precio en República Dominicana 20","item":"https://www.contactgo.net/blog/proclear-sphere-precio-republica-dominicana"}]}
    ]) }} />
    <div className="flex items-center gap-1.5 text-xs text-gray-400 mb-4"><a href="/" className="hover:text-primary-600">Inicio</a><span>/</span><a href="/blog" className="hover:text-primary-600">Blog</a><span>/</span><span className="text-gray-600 truncate">Proclear® Sphere precio en República Dom</span></div>
    <span className="text-xs font-semibold text-green-600 bg-green-50 px-2 py-0.5 rounded-full">💰 Precios 2026</span>
    <h1 className="font-display text-3xl font-bold text-gray-900 mt-3 mb-2">Proclear® Sphere precio en República Dominicana 2026</h1>
    <div className="flex items-center gap-3 mb-6 p-4 bg-blue-50 border border-blue-100 rounded-2xl">
      <div className="w-10 h-10 rounded-full bg-primary-600 flex items-center justify-center shrink-0"><span className="text-white font-bold text-sm">CG</span></div>
      <div><p className="text-sm font-bold text-gray-900">Equipo ContactGo</p><p className="text-xs text-gray-500">Especialistas en salud visual · 6 min · Julio 2026</p></div>
    </div>
    <div className="space-y-8 text-gray-700 leading-relaxed">
      <p>Los <strong>Proclear® Sphere</strong> son lentes de contacto disponibles en ContactGo a <strong>RD$3,200</strong> con entrega en 24-48 horas en toda República Dominicana. Esta guía tiene el precio actualizado, características principales y cómo pedirlos.</p>
    <section id="precio">
      <h2 className="font-display text-2xl font-bold text-gray-900 mb-4">Precio en República Dominicana — Julio 2026</h2>
      <div className="bg-green-50 border-2 border-green-200 rounded-2xl p-5 mb-4">
        <div className="flex items-baseline gap-2"><span className="text-4xl font-black text-gray-900">RD$3,200</span><span className="text-gray-500 text-sm">Caja de 6 lentes — mensual</span></div>
        <div className="flex gap-2 mt-4">
          <a href="/producto/proclear-sphere-lentes-contacto-mensuales-dominicana" className="flex-1 bg-primary-600 text-white font-bold px-4 py-2.5 rounded-xl text-xs text-center hover:bg-primary-700 transition-colors">Comprar Proclear® Sphere →</a>
          <a href="https://wa.me/18096942268" target="_blank" rel="noopener noreferrer" className="flex-1 bg-[#25D366] text-white font-bold px-4 py-2.5 rounded-xl text-xs text-center">Pedir por WhatsApp</a>
        </div>
      </div>
      <p className="text-sm text-gray-700 mt-3">Proclear Sphere es el lente mensual más económico de CooperVision en República Dominicana. Fabricado con tecnología <strong>PC Technology</strong> que incorpora fosfatidilcolina — el mismo fosfolípido de las membranas celulares humanas — para una biocompatibilidad excepcional y alta retención de humedad.</p>
    <div className="overflow-x-auto mt-4"><table className="w-full text-sm border-collapse">
      <thead><tr className="bg-gray-50"><th className="p-3 text-left border border-gray-100">Especificación</th><th className="p-3 text-right border border-gray-100">Valor</th></tr></thead>
      <tbody>
        {[['Material','Omafilcon A'],['Reemplazo','Mensual'],['Contenido agua','62%'],['Dk/t','28'],['Radio base (BC)','8.6 mm'],['Diámetro (DIA)','14.2 mm'],['Precio en RD','RD$3,200/caja de 6']].map(([k,v],i) => <tr key={i} className={i%2===0?'bg-white':'bg-gray-50'}><td className="p-3 border border-gray-100 font-medium">{k}</td><td className="p-3 border border-gray-100 text-right">{v}</td></tr>)}
      </tbody>
    </table></div>
    </section>
      <section id="productos"><h2 className="font-display text-xl font-bold text-gray-900 mb-4">Disponibles en ContactGo — Entrega 24-48h</h2>
        <div className="space-y-2">            <a href="/producto/proclear-sphere-lentes-contacto-mensuales-dominicana" className="flex items-center justify-between p-3 border border-gray-100 rounded-xl hover:border-primary-200 hover:bg-primary-50/20 transition-all group"><div><p className="text-sm font-semibold text-gray-900 group-hover:text-primary-600">Proclear® Sphere</p><p className="text-xs text-gray-500">Lentes mensuales PC Technology CooperVision</p></div><span className="font-black text-gray-900 text-sm shrink-0 ml-3">RD$3,200</span></a>
            <a href="/producto/biofinity-lentes-contacto-mensuales-coopervision-dominicana" className="flex items-center justify-between p-3 border border-gray-100 rounded-xl hover:border-primary-200 hover:bg-primary-50/20 transition-all group"><div><p className="text-sm font-semibold text-gray-900 group-hover:text-primary-600">Biofinity 6u</p><p className="text-xs text-gray-500">Caja de 6 lentes — mensual</p></div><span className="font-black text-gray-900 text-sm shrink-0 ml-3">RD$4,750</span></a></div>
        <a href="/catalogo" className="mt-3 inline-block text-sm text-primary-600 font-semibold hover:underline">Ver catálogo completo →</a>
      </section>
      <section id="faq"><h2 className="font-display text-2xl font-bold text-gray-900 mb-5">Preguntas frecuentes</h2><div className="space-y-3">          <details className="group bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden"><summary className="flex items-center justify-between p-4 cursor-pointer font-semibold text-gray-900 text-sm list-none">¿Cuánto cuestan los Proclear Sphere en República Dominicana?<svg className="w-4 h-4 text-gray-400 group-open:rotate-180 transition-transform shrink-0 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7"/></svg></summary><p className="px-4 pb-4 text-gray-600 text-sm leading-relaxed">En ContactGo los Proclear Sphere cuestan RD$3,200 la caja de 6 lentes mensuales. Son los lentes mensuales más económicos disponibles en RD, con entrega en 24-48h en toda la República Dominicana.</p></details>
          <details className="group bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden"><summary className="flex items-center justify-between p-4 cursor-pointer font-semibold text-gray-900 text-sm list-none">¿Proclear Sphere o Biofinity — cuál elegir?<svg className="w-4 h-4 text-gray-400 group-open:rotate-180 transition-transform shrink-0 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7"/></svg></summary><p className="px-4 pb-4 text-gray-600 text-sm leading-relaxed">Biofinity (RD$4,750) usa silicona hidrogel Comfilcon A con Dk/t 160 — mucho mayor oxígeno. Proclear Sphere usa hidrogel Omafilcon A con Dk/t 28. Para uso de hasta 8h, Proclear Sphere es suficiente y más económico. Para uso de 10h+, Biofinity es mejor opción.</p></details>
          <details className="group bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden"><summary className="flex items-center justify-between p-4 cursor-pointer font-semibold text-gray-900 text-sm list-none">¿Proclear Sphere es para astigmatismo?<svg className="w-4 h-4 text-gray-400 group-open:rotate-180 transition-transform shrink-0 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7"/></svg></summary><p className="px-4 pb-4 text-gray-600 text-sm leading-relaxed">No. Proclear Sphere es un lente esférico, para quienes no tienen astigmatismo (o tienen CYL muy leve no corregible con lentes de contacto). Si tienes astigmatismo (CYL en tu receta), necesitas lentes tóricos como Biofinity Toric o ACUVUE Oasys for Astigmatism.</p></details></div></section>
      <div className="grid gap-2"><h3 className="font-bold text-gray-900 text-lg">Artículos relacionados</h3>            <a href="/blog/biofinity-precio-republica-dominicana" className="border border-gray-100 rounded-xl p-3 hover:border-primary-200 hover:bg-primary-50/20 transition-all"><p className="text-sm font-semibold text-primary-600">→ Biofinity precio en RD</p><p className="text-xs text-gray-500 mt-0.5">La versión premium de CooperVision</p></a>
            <a href="/blog/lentes-diarios-vs-mensuales" className="border border-gray-100 rounded-xl p-3 hover:border-primary-200 hover:bg-primary-50/20 transition-all"><p className="text-sm font-semibold text-primary-600">→ Diarios vs mensuales</p><p className="text-xs text-gray-500 mt-0.5">Cuál conviene para ti</p></a>
            <a href="/marca/coopervision" className="border border-gray-100 rounded-xl p-3 hover:border-primary-200 hover:bg-primary-50/20 transition-all"><p className="text-sm font-semibold text-primary-600">→ Toda la línea CooperVision</p><p className="text-xs text-gray-500 mt-0.5">Biofinity, Avaira, Proclear y más</p></a></div>
    </div>
    <div className="border-l-4 border-blue-500 bg-blue-50 rounded-r-xl p-4 my-6"><p className="font-bold text-gray-900 text-sm">Verificado · Equipo ContactGo · Julio 2026</p></div>
    <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 mt-6 text-sm text-amber-900"><strong>Aviso médico:</strong> Ante molestias oculares consulta a tu especialista.</div>
    <div className="mt-10 bg-gradient-to-br from-primary-50 to-teal-50 border border-primary-100 rounded-2xl p-6 text-center">
      <h3 className="font-bold text-gray-900 text-lg mb-2">Recibe en toda República Dominicana en 24-48h</h3>
      <p className="text-sm text-gray-500 mb-4">100% originales · Pago seguro con AZUL/Banco Popular</p>
      <div className="flex flex-col sm:flex-row gap-3 justify-center">
        <a href="/catalogo" className="inline-flex items-center justify-center gap-2 bg-primary-600 text-white font-bold px-6 py-3 rounded-xl hover:bg-primary-700 transition-colors text-sm">Ver catálogo →</a>
        <a href="/receta" className="inline-flex items-center justify-center gap-2 bg-white border border-primary-200 text-primary-600 font-bold px-6 py-3 rounded-xl hover:bg-primary-50 transition-colors text-sm">Calcular mi receta</a>
        <a href="https://wa.me/18096942268" target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 bg-[#25D366] text-white font-bold px-6 py-3 rounded-xl hover:bg-[#20ba58] transition-colors text-sm">Comprar por WhatsApp</a>
      </div>
    </div>
  </main><Footer /></>)
}
