export const revalidate = 86400
import Navbar from '@/components/ui/Navbar'
import Footer from '@/components/ui/Footer'
import type { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'Lentes de contacto para trabajar con computadora — Guía 2026', description: 'Los mejores lentes de contacto para trabajar frente a la computadora. Cómo reducir la fatiga ocular digital, qué lentes usar y gotas para pantallas. Guía 2026 para RD.',
  alternates: { canonical: 'https://www.contactgo.net/blog/lentes-contacto-computadora-pantallas' },
  openGraph: { type: 'article', title: 'Lentes de contacto para trabajar con computadora y pantallas — Guía 2026', description: 'Los mejores lentes de contacto para trabajar frente a la computadora. Cómo reducir la fatiga ocular digital, qué lentes usar y gotas para pantallas. Guía 2026 para RD.', url: 'https://www.contactgo.net/blog/lentes-contacto-computadora-pantallas', siteName: 'ContactGo', locale: 'es_DO', images: [{ url: 'https://www.contactgo.net/blog/lentes-contacto-computadora-pantallas.webp', width: 1200, height: 630, alt: 'Lentes de contacto para trabajar con computadora y pantallas — Guía 2026' }] },
}
export default function Page() {
  return (<><Navbar /><main className="max-w-2xl mx-auto px-4 py-12 pb-24">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([
      {"@context":"https://schema.org","@type":"Article","headline":"Lentes de contacto para trabajar con computadora y pantallas — Guía 2026","description":"Los mejores lentes de contacto para trabajar frente a la computadora. Cómo reducir la fatiga ocular digital, qué lentes usar y gotas para pantallas. Guía 2026 para RD.","author":{"@type":"Organization","name":"Equipo ContactGo"},"publisher":{"@type":"Organization","name":"ContactGo","url":"https://www.contactgo.net","logo":{"@type":"ImageObject","url":"https://www.contactgo.net/logo.png"}},"datePublished":"2026-06-28","dateModified":"2026-06-28","url":"https://www.contactgo.net/blog/lentes-contacto-computadora-pantallas","inLanguage":"es-DO"},
      {"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":'¿Cuál es el mejor lente de contacto para trabajar con computadora?',"acceptedAnswer":{"@type":"Answer","text":'Para trabajo con pantallas, el ACUVUE Oasys con HYDRACLEAR Plus es el más recomendado por especialistas — su agente humectante interno reduce la sensación de sequedad en uso prolongado. Air Optix HydraGlyde y BL ULTRA también son excelentes opciones. Todos disponibles en ContactGo.'}},{"@type":"Question","name":'¿Cuántas horas puedo usar lentes de contacto trabajando con computadora?',"acceptedAnswer":{"@type":"Answer","text":'El máximo recomendado es 12-14 horas de uso total al día, pero para trabajo intensivo con pantallas se recomienda no más de 10-12 horas. Si usas el computador 8+ horas, considera reducir el tiempo extra de los lentes fuera del horario laboral.'}},{"@type":"Question","name":'¿Qué gotas puedo usar para la sequedad ocular frente a la pantalla?',"acceptedAnswer":{"@type":"Answer","text":'Las más efectivas y disponibles en ContactGo: Refresh Optive Advanced (RD$1,000) para sequedad moderada-severa, Refresh Optive Lubricant (RD$900) para uso regular, y Prolub Hyfresh (RD$900). Todas son compatibles con lentes de contacto blandos.'}},{"@type":"Question","name":'¿La luz azul de las pantallas daña más los ojos cuando se usan lentes de contacto?',"acceptedAnswer":{"@type":"Answer","text":'Los lentes de contacto convencionales no protegen contra la luz azul. El daño principal de las pantallas viene del parpadeo reducido (que causa ojo seco), no tanto de la luz azul en sí. ACUVUE tiene versiones con filtro UV pero no específicamente luz azul.'}}]},
      {"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Inicio","item":"https://www.contactgo.net"},{"@type":"ListItem","position":2,"name":"Blog","item":"https://www.contactgo.net/blog"},{"@type":"ListItem","position":3,"name":"Lentes de contacto para trabajar con computadora y","item":"https://www.contactgo.net/blog/lentes-contacto-computadora-pantallas"}]}
    ]) }} />
    <div className="flex items-center gap-1.5 text-xs text-gray-400 mb-4"><a href="/" className="hover:text-primary-600">Inicio</a><span>/</span><a href="/blog" className="hover:text-primary-600">Blog</a><span>/</span><span className="text-gray-600 truncate">Lentes de contacto para trabajar con com</span></div>
    <span className="text-xs font-semibold text-indigo-600 bg-indigo-50 px-2 py-0.5 rounded-full">💻 Pantallas · Fatiga ocular</span>
    <h1 className="font-display text-3xl font-bold text-gray-900 mt-3 mb-2">Lentes de contacto para trabajar con computadora y pantallas — Guía 2026</h1>
    <div className="flex items-center gap-3 mb-6 p-4 bg-blue-50 border border-blue-100 rounded-2xl">
      <div className="w-10 h-10 rounded-full bg-primary-600 flex items-center justify-center shrink-0"><span className="text-white font-bold text-sm">CG</span></div>
      <div><p className="text-sm font-bold text-gray-900">Equipo ContactGo</p><p className="text-xs text-gray-500">Especialistas en salud visual · ⏱ 8 min · Junio 2026</p></div>
    </div>
    <div className="space-y-8 text-gray-700 leading-relaxed">
      <p>Si trabajas muchas horas frente a una computadora, tablet o celular en República Dominicana, probablemente conoces la sensación: ojos secos, visión borrosa al final del día, fatiga ocular. El <strong>síndrome visual informático</strong> es real — y el lente de contacto correcto hace una diferencia enorme.</p>
        <section id="problema">
          <h2 className="font-display text-2xl font-bold text-gray-900 mb-4">Por qué las pantallas afectan los ojos con lentes</h2>
          <p>Al mirar pantallas, parpadeamos menos de lo normal: en reposo parpadeamos ~15 veces por minuto, pero frente a pantallas esa cifra cae a 5-7 veces. Cada parpadeo distribuye la película lagrimal. Menos parpadeos = más evaporación de lágrimas = ojo seco. Con lentes de contacto el problema se amplifica.</p>
          <div className="bg-indigo-50 border border-indigo-100 rounded-xl p-4 mt-4 text-sm">
            <p className="font-bold text-indigo-800 mb-1">📊 La regla 20-20-20</p>
            <p className="text-indigo-700">Cada 20 minutos, mira algo a 20 pies (~6 metros) de distancia durante 20 segundos. Esto reduce la fatiga ocular digital independientemente del tipo de lente que uses.</p>
          </div>
        </section>
        <section id="mejores">
          <h2 className="font-display text-2xl font-bold text-gray-900 mb-4">Los mejores lentes para trabajo con pantallas en RD</h2>
          <div className="space-y-3">
            {[
              { pos: 1, nombre: 'ACUVUE® Oasys®', por: 'HYDRACLEAR Plus incorpora un agente humectante que imita las lágrimas. El favorito de quienes trabajan con pantallas 8h+.', precio: 'RD$3,875', slug: 'acuvue-oasys-hydraclear-plus-lentes-contacto-quincenal-dominicana', badge: '⭐ Más recomendado para pantallas' },
              { pos: 2, nombre: 'Air Optix® plus HydraGlyde®', por: 'HydraGlyde en la superficie mantiene hidratación estable durante 16h de uso. SmartShield evita depósitos.', precio: 'RD$4,375', slug: 'air-optix-plus-hydraglyde-lentes-contacto-mensuales-dominicana', badge: 'Hidratación prolongada' },
              { pos: 3, nombre: 'Bausch+Lomb ULTRA®', por: 'MoistureSeal retiene el 95% de humedad inicial. Especialmente bueno para ambientes secos con AC.', precio: 'RD$4,500', slug: 'bausch-lomb-ultra-lentes-contacto-mensuales-dominicana', badge: 'Para AC intenso' },
              { pos: 4, nombre: 'Biofinity®', por: 'Aquaform retiene agua naturalmente. Alto Dk/t (160) para uso prolongado sin fatiga ocular.', precio: 'RD$4,750', slug: 'biofinity-lentes-contacto-mensuales-coopervision-dominicana', badge: 'Alto oxígeno' },
            ].map(l => (
              <a key={l.pos} href={`/producto/${l.slug}`} className="flex items-start gap-3 p-4 border border-gray-100 rounded-2xl hover:border-indigo-200 hover:shadow-sm transition-all group">
                <div className="w-8 h-8 bg-indigo-600 text-white rounded-full flex items-center justify-center text-sm font-black shrink-0">{l.pos}</div>
                <div className="flex-1">
                  <div className="flex items-center justify-between">
                    <div>
                      <span className="font-bold text-gray-900 text-sm group-hover:text-indigo-700">{l.nombre}</span>
                      <span className="ml-2 text-[10px] bg-indigo-50 text-indigo-600 px-1.5 py-0.5 rounded-full font-bold">{l.badge}</span>
                    </div>
                    <span className="font-black text-gray-900 shrink-0 ml-3 text-sm">{l.precio}</span>
                  </div>
                  <p className="text-xs text-gray-500 mt-0.5">{l.por}</p>
                </div>
              </a>
            ))}
          </div>
        </section>
        <section id="consejos">
          <h2 className="font-display text-2xl font-bold text-gray-900 mb-4">10 consejos para reducir la fatiga ocular trabajando con pantallas</h2>
          <ol className="space-y-2 text-sm list-decimal list-inside">
            {['Aplica la regla 20-20-20: cada 20 min, descansa 20 seg mirando a 6m de distancia.','Usa gotas lubricantes compatibles con lentes (Refresh Optive, Prolub Hyfresh) 2-3 veces al día.','Ajusta el brillo de la pantalla al mismo nivel que la luz ambiental.','Coloca la pantalla ligeramente por debajo del nivel de los ojos.','Mantén la pantalla a 50-70cm de distancia (brazo extendido).','Usa lentes de silicona hidrogel con tecnología de hidratación avanzada.','Limita a 12 horas máximo el uso de lentes en días de trabajo intenso.','Descansa los ojos sin lentes al menos 1-2 horas antes de dormir.','Ajusta la temperatura del aire acondicionado — el AC muy frío reseca los ojos.','Considera usar filtro de luz azul si tienes sensibilidad a la luz artificial.'].map((c,i) => <li key={i} className="py-1 border-b border-gray-50">{c}</li>)}
          </ol>
        </section>
      <section id="productos"><h2 className="font-display text-xl font-bold text-gray-900 mb-4">Disponibles en ContactGo — Entrega 24-48h</h2>
        <div className="space-y-2">            <a href="/producto/acuvue-oasys-hydraclear-plus-lentes-contacto-quincenal-dominicana" className="flex items-center justify-between p-3 border border-gray-100 rounded-xl hover:border-primary-200 hover:bg-primary-50/20 transition-all group"><div><p className="text-sm font-semibold text-gray-900 group-hover:text-primary-600">ACUVUE® Oasys® 6u</p><p className="text-xs text-gray-500">⭐ El favorito para pantallas</p></div><span className="font-black text-gray-900 text-sm shrink-0 ml-3">RD$3,875</span></a>
            <a href="/producto/air-optix-plus-hydraglyde-lentes-contacto-mensuales-dominicana" className="flex items-center justify-between p-3 border border-gray-100 rounded-xl hover:border-primary-200 hover:bg-primary-50/20 transition-all group"><div><p className="text-sm font-semibold text-gray-900 group-hover:text-primary-600">Air Optix® HydraGlyde® 6u</p><p className="text-xs text-gray-500">Hidratación 16h</p></div><span className="font-black text-gray-900 text-sm shrink-0 ml-3">RD$4,375</span></a>
            <a href="/producto/refresh-optive-advanced-gotas-ojos-secos-dominicana" className="flex items-center justify-between p-3 border border-gray-100 rounded-xl hover:border-primary-200 hover:bg-primary-50/20 transition-all group"><div><p className="text-sm font-semibold text-gray-900 group-hover:text-primary-600">Refresh Optive Advanced</p><p className="text-xs text-gray-500">Gotas para uso con pantallas</p></div><span className="font-black text-gray-900 text-sm shrink-0 ml-3">RD$1,000</span></a></div>
        <a href="/catalogo" className="mt-3 inline-block text-sm text-primary-600 font-semibold hover:underline">Ver catálogo completo →</a>
      </section>
      <section id="faq"><h2 className="font-display text-2xl font-bold text-gray-900 mb-5">Preguntas frecuentes</h2><div className="space-y-3">          <details className="group bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden"><summary className="flex items-center justify-between p-4 cursor-pointer font-semibold text-gray-900 text-sm list-none">¿Cuál es el mejor lente de contacto para trabajar con computadora?<svg className="w-4 h-4 text-gray-400 group-open:rotate-180 transition-transform shrink-0 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7"/></svg></summary><p className="px-4 pb-4 text-gray-600 text-sm leading-relaxed">Para trabajo con pantallas, el ACUVUE Oasys con HYDRACLEAR Plus es el más recomendado por especialistas — su agente humectante interno reduce la sensación de sequedad en uso prolongado. Air Optix HydraGlyde y BL ULTRA también son excelentes opciones. Todos disponibles en ContactGo.</p></details>
          <details className="group bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden"><summary className="flex items-center justify-between p-4 cursor-pointer font-semibold text-gray-900 text-sm list-none">¿Cuántas horas puedo usar lentes de contacto trabajando con computadora?<svg className="w-4 h-4 text-gray-400 group-open:rotate-180 transition-transform shrink-0 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7"/></svg></summary><p className="px-4 pb-4 text-gray-600 text-sm leading-relaxed">El máximo recomendado es 12-14 horas de uso total al día, pero para trabajo intensivo con pantallas se recomienda no más de 10-12 horas. Si usas el computador 8+ horas, considera reducir el tiempo extra de los lentes fuera del horario laboral.</p></details>
          <details className="group bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden"><summary className="flex items-center justify-between p-4 cursor-pointer font-semibold text-gray-900 text-sm list-none">¿Qué gotas puedo usar para la sequedad ocular frente a la pantalla?<svg className="w-4 h-4 text-gray-400 group-open:rotate-180 transition-transform shrink-0 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7"/></svg></summary><p className="px-4 pb-4 text-gray-600 text-sm leading-relaxed">Las más efectivas y disponibles en ContactGo: Refresh Optive Advanced (RD$1,000) para sequedad moderada-severa, Refresh Optive Lubricant (RD$900) para uso regular, y Prolub Hyfresh (RD$900). Todas son compatibles con lentes de contacto blandos.</p></details>
          <details className="group bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden"><summary className="flex items-center justify-between p-4 cursor-pointer font-semibold text-gray-900 text-sm list-none">¿La luz azul de las pantallas daña más los ojos cuando se usan lentes de contacto?<svg className="w-4 h-4 text-gray-400 group-open:rotate-180 transition-transform shrink-0 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7"/></svg></summary><p className="px-4 pb-4 text-gray-600 text-sm leading-relaxed">Los lentes de contacto convencionales no protegen contra la luz azul. El daño principal de las pantallas viene del parpadeo reducido (que causa ojo seco), no tanto de la luz azul en sí. ACUVUE tiene versiones con filtro UV pero no específicamente luz azul.</p></details></div></section>
      <div className="grid gap-2"><h3 className="font-bold text-gray-900 text-lg">Artículos relacionados</h3>            <a href="/blog/ojos-secos-lentes-contacto" className="border border-gray-100 rounded-xl p-3 hover:border-primary-200 hover:bg-primary-50/20 transition-all"><p className="text-sm font-semibold text-primary-600">→ Ojos secos y lentes de contacto</p><p className="text-xs text-gray-500 mt-0.5">Soluciones para la sequedad</p></a>
            <a href="/blog/gotas-para-ojos-secos-republica-dominicana" className="border border-gray-100 rounded-xl p-3 hover:border-primary-200 hover:bg-primary-50/20 transition-all"><p className="text-sm font-semibold text-primary-600">→ Mejores gotas para ojos secos en RD</p><p className="text-xs text-gray-500 mt-0.5">Comparativa de gotas lubricantes</p></a>
            <a href="/blog/cuantas-horas-usar-lentes-contacto" className="border border-gray-100 rounded-xl p-3 hover:border-primary-200 hover:bg-primary-50/20 transition-all"><p className="text-sm font-semibold text-primary-600">→ ¿Cuántas horas puedo usar lentes?</p><p className="text-xs text-gray-500 mt-0.5">Límites de uso recomendados</p></a></div>
    </div>
    <div className="border-l-4 border-blue-500 bg-blue-50 rounded-r-xl p-4 my-6"><p className="font-bold text-gray-900 text-sm">Verificado · Equipo ContactGo · Junio 2026</p></div>
    <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 mt-6 text-sm text-amber-900"><strong>⚠️ Aviso médico:</strong> Consulta a tu especialista ante cualquier duda sobre salud visual.</div>
    <div className="mt-10 bg-gradient-to-br from-primary-50 to-teal-50 border border-primary-100 rounded-2xl p-6 text-center">
      <h3 className="font-bold text-gray-900 text-lg mb-2">Recibe en toda República Dominicana en 24-48h</h3>
      <p className="text-sm text-gray-500 mb-4">100% originales · Pago seguro con AZUL</p>
      <div className="flex flex-col sm:flex-row gap-3 justify-center">
        <a href="/catalogo" className="inline-flex items-center justify-center gap-2 bg-primary-600 text-white font-bold px-6 py-3 rounded-xl hover:bg-primary-700 transition-colors text-sm">Ver catálogo →</a>
        <a href="/receta" className="inline-flex items-center justify-center gap-2 bg-white border border-primary-200 text-primary-600 font-bold px-6 py-3 rounded-xl hover:bg-primary-50 transition-colors text-sm">Calcular mi receta</a>
        <a href="https://wa.me/18096942268" target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 bg-[#25D366] text-white font-bold px-6 py-3 rounded-xl hover:bg-[#20ba58] transition-colors text-sm">Comprar por WhatsApp</a>
      </div>
    </div>
  </main><Footer /></>)
}
