export const revalidate = 86400
import Navbar from '@/components/ui/Navbar'
import Footer from '@/components/ui/Footer'
import type { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'Manzanilla Sophia precio en República Dominicana 2026 — ContactGo', description: 'Precio de Manzanilla Sophia en República Dominicana: RD$600. Para qué sirve, cómo usarla y si es compatible con lentes de contacto. Entrega 24-48h en toda RD.',
  alternates: { canonical: 'https://www.contactgo.net/blog/manzanilla-sophia-precio-republica-dominicana' },
  openGraph: { type: 'article', title: 'Manzanilla Sophia precio en República Dominicana — ¿Para qué sirve?', description: 'Precio de Manzanilla Sophia en República Dominicana: RD$600. Para qué sirve, cómo usarla y si es compatible con lentes de contacto. Entrega 24-48h en toda RD.', url: 'https://www.contactgo.net/blog/manzanilla-sophia-precio-republica-dominicana', siteName: 'ContactGo', locale: 'es_DO', images: [{ url: 'https://www.contactgo.net/blog/manzanilla-sophia-precio-republica-dominicana.webp', width: 1200, height: 630, alt: 'Manzanilla Sophia precio en República Dominicana — ¿Para qué sirve?' }] },
}
export default function Page() {
  return (<><Navbar /><main className="max-w-2xl mx-auto px-4 py-12 pb-24">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([
      {"@context":"https://schema.org","@type":"Article","headline":"Manzanilla Sophia precio en República Dominicana — ¿Para qué sirve?","description":"Precio de Manzanilla Sophia en República Dominicana: RD$600. Para qué sirve, cómo usarla y si es compatible con lentes de contacto. Entrega 24-48h en toda RD.","author":{"@type":"Organization","name":"Equipo ContactGo"},"publisher":{"@type":"Organization","name":"ContactGo","url":"https://www.contactgo.net","logo":{"@type":"ImageObject","url":"https://www.contactgo.net/logo.png"}},"datePublished":"2026-06-28","dateModified":"2026-06-28","url":"https://www.contactgo.net/blog/manzanilla-sophia-precio-republica-dominicana","inLanguage":"es-DO"},
      {"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":'¿Cuánto cuesta la Manzanilla Sophia en República Dominicana?',"acceptedAnswer":{"@type":"Answer","text":'En ContactGo la Manzanilla Sophia cuesta RD$600 el frasco. Es la opción más accesible de nuestro catálogo de gotas oftálmicas y está disponible con entrega en 24-48 horas en toda República Dominicana.'}},{"@type":"Question","name":'¿Para qué sirve la Manzanilla Sophia?',"acceptedAnswer":{"@type":"Answer","text":'La Manzanilla Sophia son gotas oftálmicas con extracto de manzanilla para aliviar la irritación ocular leve, ojos cansados y enrojecimiento sin causa infecciosa. Es un remedio natural muy popular en RD para molestias oculares cotidianas.'}},{"@type":"Question","name":'¿Se puede usar Manzanilla Sophia con lentes de contacto?',"acceptedAnswer":{"@type":"Answer","text":'No se recomienda aplicar Manzanilla Sophia con los lentes de contacto puestos. Los extractos vegetales no están formulados para compatibilidad con lentes de contacto blandos. Para usar con lentes, opta por Refresh Optive o Prolub Hyfresh, que sí son compatibles.'}},{"@type":"Question","name":'¿Dónde comprar Manzanilla Sophia en República Dominicana?',"acceptedAnswer":{"@type":"Answer","text":'En ContactGo la tienes disponible a RD$600 con entrega en 24-48 horas en toda la República Dominicana. También está disponible en farmacias locales, pero con ContactGo recibes en casa sin desplazarte.'}}]},
      {"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Inicio","item":"https://www.contactgo.net"},{"@type":"ListItem","position":2,"name":"Blog","item":"https://www.contactgo.net/blog"},{"@type":"ListItem","position":3,"name":"Manzanilla Sophia precio en República Dominicana —","item":"https://www.contactgo.net/blog/manzanilla-sophia-precio-republica-dominicana"}]}
    ]) }} />
    <div className="flex items-center gap-1.5 text-xs text-gray-400 mb-4"><a href="/" className="hover:text-primary-600">Inicio</a><span>/</span><a href="/blog" className="hover:text-primary-600">Blog</a><span>/</span><span className="text-gray-600 truncate">Manzanilla Sophia precio en República Do</span></div>
    <span className="text-xs font-semibold text-green-600 bg-green-50 px-2 py-0.5 rounded-full">💰 Precios · Gotas naturales</span>
    <h1 className="font-display text-3xl font-bold text-gray-900 mt-3 mb-2">Manzanilla Sophia precio en República Dominicana — ¿Para qué sirve?</h1>
    <div className="flex items-center gap-3 mb-6 p-4 bg-blue-50 border border-blue-100 rounded-2xl">
      <div className="w-10 h-10 rounded-full bg-primary-600 flex items-center justify-center shrink-0"><span className="text-white font-bold text-sm">CG</span></div>
      <div><p className="text-sm font-bold text-gray-900">Equipo ContactGo</p><p className="text-xs text-gray-500">Especialistas en salud visual · ⏱ 6 min · Junio 2026</p></div>
    </div>
    <div className="space-y-8 text-gray-700 leading-relaxed">
      <p>La <strong>Manzanilla Sophia</strong> es una de las gotas oftálmicas más populares en República Dominicana — usada por generaciones para el alivio de la irritación ocular con ingredientes naturales. En ContactGo la tienes disponible a RD$600 con entrega en 24-48 horas.</p>
        <section id="precio">
          <h2 className="font-display text-2xl font-bold text-gray-900 mb-4">Precio de Manzanilla Sophia en República Dominicana</h2>
          <div className="bg-green-50 border-2 border-green-200 rounded-2xl p-5">
            <div className="flex items-baseline gap-2">
              <span className="text-4xl font-black text-gray-900">RD$600</span>
              <span className="text-gray-500 text-sm">frasco de 15ml</span>
            </div>
            <p className="text-xs text-gray-500 mt-1">La opción más accesible para alivio ocular natural en RD</p>
            <div className="flex gap-2 mt-4">
              <a href="/producto/manzanilla-sophia-gotas-ojos-naturales-dominicana" className="flex-1 bg-green-600 text-white font-bold px-4 py-2.5 rounded-xl text-xs text-center hover:bg-green-700 transition-colors">Comprar Manzanilla Sophia →</a>
              <a href="https://wa.me/18295430580" target="_blank" rel="noopener noreferrer" className="flex-1 bg-[#25D366] text-white font-bold px-4 py-2.5 rounded-xl text-xs text-center">Pedir por WhatsApp</a>
            </div>
          </div>
        </section>
        <section id="para-que">
          <h2 className="font-display text-2xl font-bold text-gray-900 mb-4">¿Para qué sirve la Manzanilla Sophia?</h2>
          <p>Manzanilla Sophia son gotas oftálmicas elaboradas con extracto de manzanilla (Matricaria chamomilla), conocida por sus propiedades antiinflamatorias, calmantes y ligeramente antisépticas. Está indicada para:</p>
          <ul className="space-y-2 mt-3 text-sm">
            {['Alivio de la irritación ocular leve','Ojos cansados por uso de pantallas o lectura prolongada','Enrojecimiento ocular leve sin causa infecciosa','Sensación de arenilla o molestia leve','Refrescamiento ocular general'].map((u,i) => <li key={i} className="flex items-start gap-2"><span className="text-green-500">✓</span>{u}</li>)}
          </ul>
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mt-4 text-sm">
            <p className="font-bold text-amber-800 mb-1">⚠️ Cuándo NO usar Manzanilla Sophia</p>
            <p className="text-amber-700">No la uses si tienes conjuntivitis bacteriana, infección ocular con secreción o dolor intenso — estas condiciones requieren tratamiento médico con antibióticos. La manzanilla no sustituye el tratamiento farmacológico.</p>
          </div>
        </section>
        <section id="lentes">
          <h2 className="font-display text-2xl font-bold text-gray-900 mb-4">¿Se puede usar Manzanilla Sophia con lentes de contacto?</h2>
          <p>Este es un punto importante. Aunque la Manzanilla Sophia es popular, <strong>no está específicamente formulada como compatible con lentes de contacto blandos</strong>. Los extractos vegetales y algunos componentes pueden acumularse en el material del lente y causar irritación.</p>
          <p className="mt-3">Si usas lentes de contacto y necesitas lubricación durante el día, te recomendamos gotas específicamente formuladas para uso con lentes como <a href="/producto/refresh-optive-lubricant-gotas-oculares-dominicana" className="text-primary-600 hover:underline">Refresh Optive Lubricant</a> o <a href="/producto/prolub-hyfresh-solucion-multiproposito-dominicana" className="text-primary-600 hover:underline">Prolub Hyfresh</a>. La Manzanilla Sophia puede usarse con los lentes quitados.</p>
        </section>
      <section id="productos"><h2 className="font-display text-xl font-bold text-gray-900 mb-4">Disponibles en ContactGo — Entrega 24-48h</h2>
        <div className="space-y-2">            <a href="/producto/manzanilla-sophia-gotas-ojos-naturales-dominicana" className="flex items-center justify-between p-3 border border-gray-100 rounded-xl hover:border-primary-200 hover:bg-primary-50/20 transition-all group"><div><p className="text-sm font-semibold text-gray-900 group-hover:text-primary-600">Manzanilla Sophia</p><p className="text-xs text-gray-500">Gotas naturales · Alivio leve</p></div><span className="font-black text-gray-900 text-sm shrink-0 ml-3">RD$600</span></a>
            <a href="/producto/refresh-tears-gotas-lubricantes-ojos-dominicana" className="flex items-center justify-between p-3 border border-gray-100 rounded-xl hover:border-primary-200 hover:bg-primary-50/20 transition-all group"><div><p className="text-sm font-semibold text-gray-900 group-hover:text-primary-600">Refresh Tears</p><p className="text-xs text-gray-500">Compatible con lentes · Lágrimas artificiales</p></div><span className="font-black text-gray-900 text-sm shrink-0 ml-3">RD$800</span></a>
            <a href="/producto/refresh-optive-lubricant-gotas-oculares-dominicana" className="flex items-center justify-between p-3 border border-gray-100 rounded-xl hover:border-primary-200 hover:bg-primary-50/20 transition-all group"><div><p className="text-sm font-semibold text-gray-900 group-hover:text-primary-600">Refresh Optive Lubricant</p><p className="text-xs text-gray-500">Compatible lentes · Doble acción</p></div><span className="font-black text-gray-900 text-sm shrink-0 ml-3">RD$900</span></a></div>
        <a href="/catalogo" className="mt-3 inline-block text-sm text-primary-600 font-semibold hover:underline">Ver catálogo completo →</a>
      </section>
      <section id="faq"><h2 className="font-display text-2xl font-bold text-gray-900 mb-5">Preguntas frecuentes</h2><div className="space-y-3">          <details className="group bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden"><summary className="flex items-center justify-between p-4 cursor-pointer font-semibold text-gray-900 text-sm list-none">¿Cuánto cuesta la Manzanilla Sophia en República Dominicana?<svg className="w-4 h-4 text-gray-400 group-open:rotate-180 transition-transform shrink-0 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7"/></svg></summary><p className="px-4 pb-4 text-gray-600 text-sm leading-relaxed">En ContactGo la Manzanilla Sophia cuesta RD$600 el frasco. Es la opción más accesible de nuestro catálogo de gotas oftálmicas y está disponible con entrega en 24-48 horas en toda República Dominicana.</p></details>
          <details className="group bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden"><summary className="flex items-center justify-between p-4 cursor-pointer font-semibold text-gray-900 text-sm list-none">¿Para qué sirve la Manzanilla Sophia?<svg className="w-4 h-4 text-gray-400 group-open:rotate-180 transition-transform shrink-0 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7"/></svg></summary><p className="px-4 pb-4 text-gray-600 text-sm leading-relaxed">La Manzanilla Sophia son gotas oftálmicas con extracto de manzanilla para aliviar la irritación ocular leve, ojos cansados y enrojecimiento sin causa infecciosa. Es un remedio natural muy popular en RD para molestias oculares cotidianas.</p></details>
          <details className="group bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden"><summary className="flex items-center justify-between p-4 cursor-pointer font-semibold text-gray-900 text-sm list-none">¿Se puede usar Manzanilla Sophia con lentes de contacto?<svg className="w-4 h-4 text-gray-400 group-open:rotate-180 transition-transform shrink-0 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7"/></svg></summary><p className="px-4 pb-4 text-gray-600 text-sm leading-relaxed">No se recomienda aplicar Manzanilla Sophia con los lentes de contacto puestos. Los extractos vegetales no están formulados para compatibilidad con lentes de contacto blandos. Para usar con lentes, opta por Refresh Optive o Prolub Hyfresh, que sí son compatibles.</p></details>
          <details className="group bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden"><summary className="flex items-center justify-between p-4 cursor-pointer font-semibold text-gray-900 text-sm list-none">¿Dónde comprar Manzanilla Sophia en República Dominicana?<svg className="w-4 h-4 text-gray-400 group-open:rotate-180 transition-transform shrink-0 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7"/></svg></summary><p className="px-4 pb-4 text-gray-600 text-sm leading-relaxed">En ContactGo la tienes disponible a RD$600 con entrega en 24-48 horas en toda la República Dominicana. También está disponible en farmacias locales, pero con ContactGo recibes en casa sin desplazarte.</p></details></div></section>
      <div className="grid gap-2"><h3 className="font-bold text-gray-900 text-lg">Artículos relacionados</h3>            <a href="/blog/gotas-para-ojos-secos-republica-dominicana" className="border border-gray-100 rounded-xl p-3 hover:border-primary-200 hover:bg-primary-50/20 transition-all"><p className="text-sm font-semibold text-primary-600">→ Las mejores gotas para ojos secos en RD</p><p className="text-xs text-gray-500 mt-0.5">Comparativa de todas las opciones</p></a>
            <a href="/blog/refresh-optive-precio-republica-dominicana" className="border border-gray-100 rounded-xl p-3 hover:border-primary-200 hover:bg-primary-50/20 transition-all"><p className="text-sm font-semibold text-primary-600">→ Refresh Optive precio en RD</p><p className="text-xs text-gray-500 mt-0.5">La alternativa farmacológica</p></a>
            <a href="/blog/ojos-secos-lentes-contacto" className="border border-gray-100 rounded-xl p-3 hover:border-primary-200 hover:bg-primary-50/20 transition-all"><p className="text-sm font-semibold text-primary-600">→ Ojos secos y lentes de contacto</p><p className="text-xs text-gray-500 mt-0.5">Gotas compatibles con lentes</p></a></div>
    </div>
    <div className="border-l-4 border-blue-500 bg-blue-50 rounded-r-xl p-4 my-6"><p className="font-bold text-gray-900 text-sm">Verificado · Equipo ContactGo · Junio 2026</p></div>
    <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 mt-6 text-sm text-amber-900"><strong>⚠️ Aviso médico:</strong> Consulta a tu especialista ante cualquier duda sobre salud visual.</div>
    <div className="mt-10 bg-gradient-to-br from-primary-50 to-teal-50 border border-primary-100 rounded-2xl p-6 text-center">
      <h3 className="font-bold text-gray-900 text-lg mb-2">Recibe en toda República Dominicana en 24-48h</h3>
      <p className="text-sm text-gray-500 mb-4">100% originales · Pago seguro con AZUL</p>
      <div className="flex flex-col sm:flex-row gap-3 justify-center">
        <a href="/catalogo" className="inline-flex items-center justify-center gap-2 bg-primary-600 text-white font-bold px-6 py-3 rounded-xl hover:bg-primary-700 transition-colors text-sm">Ver catálogo →</a>
        <a href="/receta" className="inline-flex items-center justify-center gap-2 bg-white border border-primary-200 text-primary-600 font-bold px-6 py-3 rounded-xl hover:bg-primary-50 transition-colors text-sm">Calcular mi receta</a>
        <a href="https://wa.me/18295430580" target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 bg-[#25D366] text-white font-bold px-6 py-3 rounded-xl hover:bg-[#20ba58] transition-colors text-sm">Comprar por WhatsApp</a>
      </div>
    </div>
  </main><Footer /></>)
}
