export const revalidate = 86400
import Navbar from '@/components/ui/Navbar'
import Footer from '@/components/ui/Footer'
import type { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'Biofinity XR precio en República Dominicana 2026 — Alta graduación', description: 'Precio de Biofinity XR en RD: esférico RD$5,500 · Toric RD$12,000. Lentes para alta graduación CooperVision. Disponibles en ContactGo con entrega 24-48h en toda RD.',
  alternates: { canonical: 'https://www.contactgo.net/blog/biofinity-xr-precio-republica-dominicana' },
  openGraph: { type: 'article', title: 'Biofinity® XR precio en República Dominicana 2026 — Lentes para alta graduación', description: 'Precio de Biofinity XR en RD: esférico RD$5,500 · Toric RD$12,000. Lentes para alta graduación CooperVision. Disponibles en ContactGo con entrega 24-48h en toda RD.', url: 'https://www.contactgo.net/blog/biofinity-xr-precio-republica-dominicana', siteName: 'ContactGo', locale: 'es_DO', images: [{ url: 'https://www.contactgo.net/blog/biofinity-xr-precio-republica-dominicana.webp', width: 1200, height: 630, alt: 'Biofinity® XR precio en República Dominicana 2026 — Lentes para alta graduación' }] },
}
export default function Page() {
  return (<><Navbar /><main className="max-w-2xl mx-auto px-4 py-12 pb-24">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([
      {"@context":"https://schema.org","@type":"Article","headline":"Biofinity® XR precio en República Dominicana 2026 — Lentes para alta graduación","description":"Precio de Biofinity XR en RD: esférico RD$5,500 · Toric RD$12,000. Lentes para alta graduación CooperVision. Disponibles en ContactGo con entrega 24-48h en toda RD.","author":{"@type":"Organization","name":"Equipo ContactGo"},"publisher":{"@type":"Organization","name":"ContactGo","url":"https://www.contactgo.net","logo":{"@type":"ImageObject","url":"https://www.contactgo.net/logo.png"}},"datePublished":"2026-07-02","dateModified":"2026-07-02","url":"https://www.contactgo.net/blog/biofinity-xr-precio-republica-dominicana","inLanguage":"es-DO"},
      {"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":'¿Cuánto cuestan los Biofinity XR en República Dominicana?',"acceptedAnswer":{"@type":"Answer","text":'En ContactGo: Biofinity XR esférico RD$5,500 (6u mensual) y Biofinity XR Toric RD$12,000 (6u mensual para alta graduación con astigmatismo). Entrega en 24-48h en toda República Dominicana.'}},{"@type":"Question","name":'¿Cuál es la diferencia entre Biofinity y Biofinity XR?',"acceptedAnswer":{"@type":"Answer","text":'Biofinity cubre SPH de -6.00 a +6.00 aproximadamente. Biofinity XR amplía el rango hasta -20.00 / +15.00 en esférico. Usan el mismo material (Comfilcon A) y tecnología Aquaform — la diferencia es el rango de graduación disponible.'}},{"@type":"Question","name":'¿Para qué es el Biofinity XR Toric?',"acceptedAnswer":{"@type":"Answer","text":'Para personas con alta graduación esférica (miopes/hipermétropes fuertes) que TAMBIÉN tienen astigmatismo. Es uno de los pocos lentes disponibles en RD que combina alto rango de SPH con corrección de CYL hasta -5.75.'}},{"@type":"Question","name":'¿Dónde comprar Biofinity XR en República Dominicana?',"acceptedAnswer":{"@type":"Answer","text":'En ContactGo tienes Biofinity XR y Biofinity XR Toric originales de CooperVision con entrega en 24-48h en toda la República Dominicana. Pago seguro con AZUL/Banco Popular.'}}]},
      {"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Inicio","item":"https://www.contactgo.net"},{"@type":"ListItem","position":2,"name":"Blog","item":"https://www.contactgo.net/blog"},{"@type":"ListItem","position":3,"name":"Biofinity® XR precio en República Dominicana 2026 ","item":"https://www.contactgo.net/blog/biofinity-xr-precio-republica-dominicana"}]}
    ]) }} />
    <div className="flex items-center gap-1.5 text-xs text-gray-400 mb-4"><a href="/" className="hover:text-primary-600">Inicio</a><span>/</span><a href="/blog" className="hover:text-primary-600">Blog</a><span>/</span><span className="text-gray-600 truncate">Biofinity® XR precio en República Domini</span></div>
    <span className="text-xs font-semibold text-blue-600 bg-blue-50 px-2 py-0.5 rounded-full">💰 Alta graduación · Precios</span>
    <h1 className="font-display text-3xl font-bold text-gray-900 mt-3 mb-2">Biofinity® XR precio en República Dominicana 2026 — Lentes para alta graduación</h1>
    <div className="flex items-center gap-3 mb-6 p-4 bg-blue-50 border border-blue-100 rounded-2xl">
      <div className="w-10 h-10 rounded-full bg-primary-600 flex items-center justify-center shrink-0"><span className="text-white font-bold text-sm">CG</span></div>
      <div><p className="text-sm font-bold text-gray-900">Equipo ContactGo</p><p className="text-xs text-gray-500">Especialistas en salud visual · 7 min · Julio 2026</p></div>
    </div>
    <div className="space-y-8 text-gray-700 leading-relaxed">
      <p>Los <strong>Biofinity® XR</strong> de CooperVision son la solución para personas con <strong>graduación alta o extrema</strong> que no pueden corregirse con lentes de contacto convencionales. En República Dominicana están disponibles en ContactGo en versión esférica y tórica.</p>
    <section id="precios">
      <h2 className="font-display text-2xl font-bold text-gray-900 mb-4">Precios Biofinity XR en RD — Julio 2026</h2>
      <div className="overflow-x-auto"><table className="w-full text-sm border-collapse">
        <thead><tr className="bg-blue-50"><th className="p-3 text-left border border-gray-100 font-bold">Producto</th><th className="p-3 text-center border border-gray-100 font-bold">Indicación</th><th className="p-3 text-right border border-gray-100 font-bold">Precio RD$</th></tr></thead>
        <tbody>
          <tr className="bg-white"><td className="p-3 border border-gray-100"><a href="/producto/biofinity-xr-lentes-alta-graduacion-dominicana" className="text-primary-600 font-medium hover:underline">Biofinity® XR 6u</a></td><td className="p-3 border border-gray-100 text-center text-gray-500">Alta graduación esférica</td><td className="p-3 border border-gray-100 text-right font-black">RD$5,500</td></tr>
          <tr className="bg-gray-50"><td className="p-3 border border-gray-100"><a href="/producto/biofinity-xr-toric-lentes-alta-graduacion-astigmatismo-dominicana" className="text-primary-600 font-medium hover:underline">Biofinity® XR Toric 6u</a></td><td className="p-3 border border-gray-100 text-center text-gray-500">Alta graduación + astigmatismo</td><td className="p-3 border border-gray-100 text-right font-black">RD$12,000</td></tr>
        </tbody>
      </table></div>
    </section>
    <section id="que-es">
      <h2 className="font-display text-2xl font-bold text-gray-900 mb-4">¿Para quién es el Biofinity XR?</h2>
      <p className="text-sm text-gray-700">El Biofinity XR amplía el rango de corrección más allá del Biofinity estándar. Está indicado para personas con:</p>
      <ul className="space-y-2 mt-3 text-sm">
        {[
          'SPH de -12.00 a -20.00 o de +8.00 a +15.00 (rango extendido)',
          'CYL de hasta -5.75 (versión XR Toric)',
          'Alta miopía o hipermetropía que no puede corregirse con lentes convencionales',
          'Personas que han sido informadas de que no pueden usar lentes de contacto por su graduación alta',
        ].map((item, i) => <li key={i} className="flex items-start gap-2"><span className="text-blue-500">→</span>{item}</li>)}
      </ul>
      <div className="bg-blue-50 border border-blue-100 rounded-xl p-4 mt-4 text-sm">
        <p className="font-bold text-blue-800 mb-1">💡 Caso real: el cliente de Constanza</p>
        <p className="text-blue-700">Un usuario con SPH -12 puede usar Biofinity esférico estándar (hasta -12) o Biofinity XR. Para SPH -13 o mayor, el XR es la única opción en lentes mensuales de silicona hidrogel disponibles en ContactGo.</p>
      </div>
    </section>
      <section id="productos"><h2 className="font-display text-xl font-bold text-gray-900 mb-4">Disponibles en ContactGo — Entrega 24-48h</h2>
        <div className="space-y-2">            <a href="/producto/biofinity-xr-lentes-alta-graduacion-dominicana" className="flex items-center justify-between p-3 border border-gray-100 rounded-xl hover:border-primary-200 hover:bg-primary-50/20 transition-all group"><div><p className="text-sm font-semibold text-gray-900 group-hover:text-primary-600">Biofinity XR 6u</p><p className="text-xs text-gray-500">Alta graduación esférica — mensual</p></div><span className="font-black text-gray-900 text-sm shrink-0 ml-3">RD$5,500</span></a>
            <a href="/producto/biofinity-xr-toric-lentes-alta-graduacion-astigmatismo-dominicana" className="flex items-center justify-between p-3 border border-gray-100 rounded-xl hover:border-primary-200 hover:bg-primary-50/20 transition-all group"><div><p className="text-sm font-semibold text-gray-900 group-hover:text-primary-600">Biofinity XR Toric 6u</p><p className="text-xs text-gray-500">Alta grad. + astigmatismo — mensual</p></div><span className="font-black text-gray-900 text-sm shrink-0 ml-3">RD$12,000</span></a>
            <a href="/producto/biofinity-lentes-contacto-mensuales-coopervision-dominicana" className="flex items-center justify-between p-3 border border-gray-100 rounded-xl hover:border-primary-200 hover:bg-primary-50/20 transition-all group"><div><p className="text-sm font-semibold text-gray-900 group-hover:text-primary-600">Biofinity 6u</p><p className="text-xs text-gray-500">Estándar mensual CooperVision</p></div><span className="font-black text-gray-900 text-sm shrink-0 ml-3">RD$4,750</span></a></div>
        <a href="/catalogo" className="mt-3 inline-block text-sm text-primary-600 font-semibold hover:underline">Ver catálogo completo →</a>
      </section>
      <section id="faq"><h2 className="font-display text-2xl font-bold text-gray-900 mb-5">Preguntas frecuentes</h2><div className="space-y-3">          <details className="group bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden"><summary className="flex items-center justify-between p-4 cursor-pointer font-semibold text-gray-900 text-sm list-none">¿Cuánto cuestan los Biofinity XR en República Dominicana?<svg className="w-4 h-4 text-gray-400 group-open:rotate-180 transition-transform shrink-0 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7"/></svg></summary><p className="px-4 pb-4 text-gray-600 text-sm leading-relaxed">En ContactGo: Biofinity XR esférico RD$5,500 (6u mensual) y Biofinity XR Toric RD$12,000 (6u mensual para alta graduación con astigmatismo). Entrega en 24-48h en toda República Dominicana.</p></details>
          <details className="group bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden"><summary className="flex items-center justify-between p-4 cursor-pointer font-semibold text-gray-900 text-sm list-none">¿Cuál es la diferencia entre Biofinity y Biofinity XR?<svg className="w-4 h-4 text-gray-400 group-open:rotate-180 transition-transform shrink-0 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7"/></svg></summary><p className="px-4 pb-4 text-gray-600 text-sm leading-relaxed">Biofinity cubre SPH de -6.00 a +6.00 aproximadamente. Biofinity XR amplía el rango hasta -20.00 / +15.00 en esférico. Usan el mismo material (Comfilcon A) y tecnología Aquaform — la diferencia es el rango de graduación disponible.</p></details>
          <details className="group bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden"><summary className="flex items-center justify-between p-4 cursor-pointer font-semibold text-gray-900 text-sm list-none">¿Para qué es el Biofinity XR Toric?<svg className="w-4 h-4 text-gray-400 group-open:rotate-180 transition-transform shrink-0 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7"/></svg></summary><p className="px-4 pb-4 text-gray-600 text-sm leading-relaxed">Para personas con alta graduación esférica (miopes/hipermétropes fuertes) que TAMBIÉN tienen astigmatismo. Es uno de los pocos lentes disponibles en RD que combina alto rango de SPH con corrección de CYL hasta -5.75.</p></details>
          <details className="group bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden"><summary className="flex items-center justify-between p-4 cursor-pointer font-semibold text-gray-900 text-sm list-none">¿Dónde comprar Biofinity XR en República Dominicana?<svg className="w-4 h-4 text-gray-400 group-open:rotate-180 transition-transform shrink-0 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7"/></svg></summary><p className="px-4 pb-4 text-gray-600 text-sm leading-relaxed">En ContactGo tienes Biofinity XR y Biofinity XR Toric originales de CooperVision con entrega en 24-48h en toda la República Dominicana. Pago seguro con AZUL/Banco Popular.</p></details></div></section>
      <div className="grid gap-2"><h3 className="font-bold text-gray-900 text-lg">Artículos relacionados</h3>            <a href="/blog/biofinity-precio-republica-dominicana" className="border border-gray-100 rounded-xl p-3 hover:border-primary-200 hover:bg-primary-50/20 transition-all"><p className="text-sm font-semibold text-primary-600">→ Toda la línea Biofinity en RD</p><p className="text-xs text-gray-500 mt-0.5">Esférico, Toric, XR, Multifocal</p></a>
            <a href="/blog/lentes-astigmatismo-precio-republica-dominicana" className="border border-gray-100 rounded-xl p-3 hover:border-primary-200 hover:bg-primary-50/20 transition-all"><p className="text-sm font-semibold text-primary-600">→ Lentes para astigmatismo en RD</p><p className="text-xs text-gray-500 mt-0.5">Todos los tóricos disponibles</p></a>
            <a href="/blog/como-leer-receta-optica-rd" className="border border-gray-100 rounded-xl p-3 hover:border-primary-200 hover:bg-primary-50/20 transition-all"><p className="text-sm font-semibold text-primary-600">→ Cómo leer tu receta óptica</p><p className="text-xs text-gray-500 mt-0.5">Entender SPH, CYL y AXIS</p></a></div>
    </div>
    <div className="border-l-4 border-blue-500 bg-blue-50 rounded-r-xl p-4 my-6"><p className="font-bold text-gray-900 text-sm">Verificado · Equipo ContactGo · Julio 2026</p></div>
    <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 mt-6 text-sm text-amber-900"><strong>Aviso médico:</strong> Ante molestias oculares consulta a tu especialista.</div>
    <div className="mt-10 bg-gradient-to-br from-primary-50 to-teal-50 border border-primary-100 rounded-2xl p-6 text-center">
      <h3 className="font-bold text-gray-900 text-lg mb-2">Recibe en toda República Dominicana en 24-48h</h3>
      <p className="text-sm text-gray-500 mb-4">100% originales · Pago seguro con AZUL/Banco Popular</p>
      <div className="flex flex-col sm:flex-row gap-3 justify-center">
        <a href="/catalogo" className="inline-flex items-center justify-center gap-2 bg-primary-600 text-white font-bold px-6 py-3 rounded-xl hover:bg-primary-700 transition-colors text-sm">Ver catálogo →</a>
        <a href="/receta" className="inline-flex items-center justify-center gap-2 bg-white border border-primary-200 text-primary-600 font-bold px-6 py-3 rounded-xl hover:bg-primary-50 transition-colors text-sm">Calcular mi receta</a>
        <a href="https://wa.me/18294728328" target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 bg-[#25D366] text-white font-bold px-6 py-3 rounded-xl hover:bg-[#20ba58] transition-colors text-sm">Comprar por WhatsApp</a>
      </div>
    </div>
  </main><Footer /></>)
}
